Frontends/CarBook.WebUI/Controllers/AdminBrandController.cs
using CarBook.Dto.BrandDtos;
using CarBook.Dto.FeatureDtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace CarBook.WebUI.Controllers
{
    public class AdminBrandController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public AdminBrandController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();

            var responseMessge = await client.GetAsync("http://localhost:5041/api/Brand");
            if (responseMessge.IsSuccessStatusCode)
            {
                var jsonData = await responseMessge.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultBrandDto>>(jsonData);
                return View(values);
            }
            return View();
        }
        public IActionResult CreateBrand()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateBrand(CreateBrandDto dto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(dto);
            StringContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PostAsync("http://localhost:5041/api/Brand", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<IActionResult> DeleteBrand(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.DeleteAsync($"http://localhost:5041/api/Brand/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<IActionResult> UpdateBrand(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"http://localhost:5041/api/Brand/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<UpdateBrandDto>(jsonData);
                return View(values);
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBrand(UpdateBrandDto dto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(dto);
            StringContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync("http://localhost:5041/api/Brand", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View(dto);
        }
    }
}

Frontends/CarBook.WebUI/Views/AdminBrand/CreateBrand.cshtml
@model CreateBrandDto
@{
    ViewData["Title"] = "CreateBrand";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">

                    <h4 class="card-title">Yeni Marka </h4>
                    <p class="card-subtitle mb-4">Marka Ekleyin</p>

                    <form method="post" asp-action="CreateBrand" asp-controller="AdminBrand">

                        <div class="form-group">
                            <label for="exampleInputBrandName">Marka</label>
                            <input asp-for="@Model.brandName" type="text" class="form-control" placeholder="Marka İsmini Giriniz" />
                        </div>

                        <button type="submit" class="btn btn-primary waves-effect waves-light">Marka Ekle</button>
                    </form>

                </div> <!-- end card-body-->
            </div>

        </div>
    </div>
</div>

Frontends/CarBook.WebUI/Views/AdminBrand/Index.cshtml
@model List<ResultBrandDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/AdminLayout/Index.cshtml";
    int count = 0;
}

<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Marka Listesi</h4>
                    <p class="card-subtitle mb-4">
                       Araba Markaları İle İlgili Ekleme, Silme Güncelleme İşlemleri Yapabilirisiniz
                    </p>
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Marka</th>

                                    <th>Sil</th>

                                    <th>Güncelle</th>
                                    <th>Markaya Ait Araçlar</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    count = count + 1;
                                    <tr>
                                        <th scope="row">@count</th>
                                        <td>@item.brandName</td>

                                        <td><a href="/AdminBrand/DeleteBrand/@item.brandId" class="btn  btn-outline-danger">Sil</a></td>
                                        <td><a href="/AdminBrand/UpdateBrand/@item.brandId" class="btn btn-outline-success">Güncelle</a></td>
                                        <td><a href="/AdminBrand/UpdateBrand/@item.brandId" class="btn btn-outline-dark">Araçlar</a></td>



                                    </tr>

                                }


                            </tbody>
                        </table>
                        <br />
                        <a href="/AdminBrand/CreateBrand" class="btn btn-primary">Yeni Marka Girişi</a>

                    </div>

                </div>
                <!-- end card-body-->
            </div>
            <!-- end card -->

        </div>
        <!-- end col -->
        <!-- end col -->
    </div>
    <!-- end page title -->

</div>

Frontends/CarBook.WebUI/Views/AdminBrand/UpdateBrand.cshtml
@model UpdateBrandDto
@{
    ViewData["Title"] = "UpdateBrand";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">

                    <h4 class="card-title">Marka Güncelle </h4>
                    <p class="card-subtitle mb-4">Araçlar ile ilgili  marka güncelleyiniz.</p>

                    <form method="post" asp-action="UpdateBrand" asp-controller="AdminBrand">
                        <input type="hidden" asp-for="brandId" />
                        <div class="form-group">
                            <label for="exampleInputFeatureName">Marka</label>
                            <input asp-for="@Model.brandName" type="text" class="form-control" placeholder="Marka İsmini Giriniz" />
                        </div>

                        <button type="submit" class="btn btn-primary waves-effect waves-light">Marka Güncelle</button>
                    </form>

                </div> <!-- end card-body-->
            </div>

        </div>
    </div>
</div>